name: aliya-cosmos

services:
  neo4j:
    image: neo4j:latest
    container_name: aliya-cosmos-neo4j
    volumes:
      - ../data/Neo4j/logs:/logs
      - ../data/Neo4j/data:/data
      - ../data/Neo4j/plugins:/plugins
      - ../data/Neo4j/config:/config
    environment:
        - NEO4J_AUTH=neo4j/Aliya_neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always

  astratts:
    build:
      context: ../data/AstraTTS
      dockerfile: Dockerfile
    image: astratts-server:latest
    container_name: aliya-cosmos-astratts
    ports:
      - "5000:5000"
    volumes:
      - ../data/AstraTTS/resources:/app/resources
      - type: bind
        source: ../data/AstraTTS/config.yaml
        target: /app/config.yaml
    restart: unless-stopped

